### ISSUE TITLE
Remove `crayon` from dependencies

### ISSUE THREAD

**Issue by pawelru** [insightsengineering/teal.code#102]
`crayon` package has been superseded in favour of `cli`. Please update the codebase accordingly.

----
It looks like we are using only one function from it in only one place. I would strongly suggest to consider removing this dependency at all.

**Comment by nikolas-burkoff** [comment]
So the function is used in the chunks part of the package which will be removed when possible -> though I think we can use the internal function .ansi_strip to do the same thing https://github.com/insightsengineering/teal.code/blob/main/R/qenv-eval_code.R#L96

**Comment by donyunardi** [comment]
Code in questions:
https://github.com/insightsengineering/teal.code/blob/89f07c138f43d7fadaf8a03f8d46f211e3e6720d/R/get_eval_details.R#L42-L46

### Acceptance Criteria
* Remove `crayon` usage, update to `cli` functions
* Remove `crayon` dependency

**Comment by donyunardi** [comment]
Decided to reopen this issue so we can handle it together with the roadmap on removing chunk codebase.
