### ISSUE TITLE
Introduce `within.qenv`

### ISSUE THREAD

**Issue by gogonzo** [insightsengineering/teal.code#127]
As an alternative to `eval_code`, `within` could be a nice way of specifying the code. Most important thing about this function should be substitution of dynamic symbols. We need to be able to have a full control over a call. 

```r
qenv <- new_qenv() |> within(qenv, {
  iris2 <- dplyr::filter(iris, {varname} = {as.character(var_value)})
})
```

`eval_code` shouldn't be discontinued, as it is still important to have a way of evaluating `character` or `language`.

Update:
- `within` should have arguments:
     -  `expr` literal R expression 
     - `code` R object containing valid R expression (class - language, expression or character)
     - `...` replacement arguments similar to `env` in substitute

**Comment by chlebowa** [comment]
I have been working on a prototype but my assumption so far were slightly different:
1. `qenv` is an environment, not an S4 object holding an environment in a slot
2. code and condition messages are stored in attributes, not slots
3. all code is evaluated in the `qenv`, modifying it by reference, not returning a (deep copy)
4. syntax is based on the S3 generic `with` and code is passed as expressions:
```
q <- qenv()
with(q, i <- iris)
```

Changing `with` to `within` and having the function return a copy is easy enough. Actually, a `within` method could be added alongside the `with` one.

My suggestions and more details can be found in the `__new_qenv.R` file [here](https://github.com/insightsengineering/teal.code/pull/136).
