### ISSUE TITLE
[Question]: Should we return the code, where all default parameters are returned for function calls?

### ISSUE THREAD

**Issue by m7pr** [insightsengineering/teal.code#128]
### What is your question?

Imagine a situation where we return the reproducible code like below
`data.frame(X = 1:2, Y = letters[1:2])`
This simple code gives different results depending on R version, since default parameters, like `stringsAsFactors` might change depending on R version. This could also be a function in a package, that changed defaults between different versions of the development cycle.

What if we always return the necessary code, but for all used function we also return their calls with currently used defaults? An example for the `data.frame` call would look like below

```{R}
data.frame(X = 1:2, Y = letters[1:2], row.names = NULL, check.rows = FALSE,
           check.names = TRUE, fix.empty.names = TRUE,
           stringsAsFactors = FALSE)
```

I know that we might/may return the session info, and renv.lock at some point, or even a docker container specification. However I reckon this brings greater reproducibility if we specify functions with an actual usage of their default parameters, in case session info is missing or session info is not restorable.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

### Contribution Guidelines

- [X] I agree to follow this project's Contribution Guidelines.

### Security Policy

- [X] I agree to follow this project's Security Policy.

**Comment by m7pr** [comment]
cc @donyunardi @gogonzo @chlebowa 
You might be interested as you might be involved in the upcoming refactor of the way we specify the code in `teal::init`

**Comment by gogonzo** [comment]
I think we should return only what has been specified in a call explicitly. Dependencies will be handled by returned renv file (as you mentioned), so we don't need to bother about environment differences. Some functions have too many arguments, and SRC (show R code) will become less readable.

**Comment by chlebowa** [comment]
I agree, some functions have just too many arguments.
My skepticism of `renv` aside, dependencies should be provided by the party reusing the code, we provide all the necessary information.

**Comment by m7pr** [comment]
Having seconds thoughts on this one. Indeed managing reproducibility is often taking a burdening step of introducing inconvenient solutions, but here the renv/docker help will satisfy the dependency requirement of reproducibility. I take a step back on this idea.

However when it comes to `renv`, it's better to have it than not because at least you have a unique list of package versions that were used (thanks to `renv.lock` file). And even though `renv::restore()` might not work, at some point humanity can invent something better than `renv::restore()` that uses `renv.lock` or at least you can call `versions::install_version` on your own, to get all needed packages, but manually in a tedious way : )

Lastly, my approach to reproducibility is that you provide environment, next to the code, and you store all input artifacts and output results for the future comparison on the reproducibility process. Not necessarily it is our duty - maybe we can team up with IDR on this.

**Comment by chlebowa** [comment]
> when it comes to `renv`, it's better to have it than not

Agree to disagree :wink:

**Comment by m7pr** [comment]
You can always disable it by the removal of the `source('renv/activate.R')` in `.Rprofile`. I know `renv` is not ideal, but the problem of reproducibility is not trivial. We need to keep using (even bugged) tools to find the ways to improve them.
