### ISSUE TITLE
[Question]: Should we return Docker Image instructions with R code?

### ISSUE THREAD

**Issue by m7pr** [insightsengineering/teal.code#130]
### What is your question?

Currently with R code, we are returning and information on needed libraries, data preparations, hashes or R objects and all needed filters and further data processing to reproduce the analysis. The key element of the reproducibility, next to instructions (the code), is the environment. @cicdguy is planning to create Docker Images with released versions of teal packages. I reckon it would be a great addition, if next to libraries and other calls that I mentioned above, we would return an information on how to pull a Docker Image and how to start it to launch an environment where the code was executed on the app side.

This would probably be an addition of 2 commented lines to the returned code, like the stuff below

```{R}
# if you want to pull a reproducible environment in which this code was run during your interactive analysis follow below
# 1. Install Docker Image [some link with instructions]
# 2. Pull our Docker Image [link with instructions]
# 3. Start our Docker Image as a Container [instructions]
```

That is basically 3 lines, but improves the robustness of the reproducibility.

CC @gogonzo @donyunardi and @chlebowa as I know you are a fan of reproducible research

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

### Contribution Guidelines

- [X] I agree to follow this project's Contribution Guidelines.

### Security Policy

- [X] I agree to follow this project's Security Policy.

**Comment by donyunardi** [comment]
Thank you for the question @m7pr 
I understand your point.

With the current `Show R Code` feature, it only displays the packages being loaded in the session but not their versions. 

teal frameworks might be straightforward to identify, but the issue arises with their dependencies. For instance, if the `Show R Code` includes `library(shinyTree)`, it's unclear which version should be used. It may be assumed to be the latest version, but this isn't always guaranteed.

Regarding your suggestion about adding a comment line for Docker images, it seems to promote the use of the Docker image provided during teal development. However, if a user wishes to use a different development version of some packages, the comment becomes irrelevant.

Here's an alternative solution: perhaps we can display a full `sessionInfo()` somewhere, including package versions. This way, it's up to the users to ensure that they match the versions themselves. This could also be an easier entry point for those who's not familiar with Docker.

**Comment by donyunardi** [comment]
There's a related issue on this topic:
https://github.com/insightsengineering/coredev-tasks/issues/479

The suggestion is to provide an renv lockfile.

**Comment by m7pr** [comment]
OK, thanks for letting me know that there is already an issue for that. Closing this one
