### ISSUE TITLE
Release `teal.code` to CRAN

### ISSUE THREAD

**Issue by donyunardi** [insightsengineering/teal.code#132]
### Summary
The objective is to make `teal.code` available on CRAN. However, a preliminary release is necessary due to minor issue when R CMD check is performed.

### Prereq
* https://github.com/insightsengineering/teal.code/issues/137

### Acceptance Criteria
* [x] Update README as directed [here](https://github.com/insightsengineering/coredev-tasks/issues/462)
* [x] ~Group vignettes in a meaningful cohorts as directed [here](https://github.com/insightsengineering/coredev-tasks/issues/468)~
* [X] Add/Confirm the `--as-cran` option in CICD pipeline
* [x]  R CMD Check passed or create new issue to fix
* [x] CRAN and GH Release

**Comment by donyunardi** [comment]
> Add/Confirm the --as-cran option in CICD pipeline

Confirmed:
https://github.com/insightsengineering/teal.code/blob/main/.github/workflows/check.yaml#L30

**Comment by gogonzo** [comment]
Comments from CRAN

> If there are references describing the methods in your package, please
add these in the description field of your DESCRIPTION file in the form
authors (year) <doi:...>
authors (year) <arXiv:...>
authors (year, ISBN:...)
or if those are not available: <https:...>
with no space after 'doi:', 'arXiv:', 'https:' and angle brackets for
auto-linking.
(If you want to add a title as well please put it in quotes: "Title")

> Please add \value to .Rd files regarding exported methods and explain
the functions results in the documentation. Please write about the
structure of the output (class) and also what the output means. (If a
function does not return a value, please document that too, e.g.
\value{No return value, called for side effects} or similar)
Missing Rd-tags: dev_suppress.Rd: \value



> Please do not modifiy the .GlobalEnv. This is not allowed by the CRAN
policies.

Regarding .GlobalEnv I started discussion with CRAN - I think it's a misunderstanding. Let's wait for the response

**Comment by m7pr** [comment]
I don't understand this part. Do they refer to methods, in the form of a scientific paper that invented some method? I don't think we have that or reference anything. So I would skip this feedback.

```
If there are references describing the methods in your package, please
add these in the description field of your DESCRIPTION file in the form
authors (year) doi:...
authors (year) arXiv:...
authors (year, ISBN:...)
or if those are not available: [https:...](https://github.com/insightsengineering/teal.code/issues/...)
with no space after 'doi:', 'arXiv:', 'https:' and angle brackets for
auto-linking.
(If you want to add a title as well please put it in quotes: "Title")
```

**Comment by m7pr** [comment]
Addressed 

```
Please add \value to .Rd files regarding exported methods and explain
the functions results in the documentation. Please write about the
structure of the output (class) and also what the output means. (If a
function does not return a value, please document that too, e.g.
\value{No return value, called for side effects} or similar)
Missing Rd-tags: dev_suppress.Rd: \value
```

in here ee8e1504c42223611c370139932332cbbca3e28b

**Comment by gogonzo** [comment]
> Regarding .GlobalEnv I started discussion with CRAN - I think it's a misunderstanding. Let's wait for the response
They (CRAN) accepted .GlobalEnv occurrences in the package, so if other issues are fixed we can resubmit

**Comment by m7pr** [comment]
teal.code released on CRAN
https://cran.r-project.org/web/packages/teal.code/index.html
