### ISSUE TITLE
Don't allow to specify initial env and a code

### ISSUE THREAD

**Issue by gogonzo** [insightsengineering/teal.code#145]
`qenv` is a low level reproducibility tool. To make things simple as possible let's skip the case where we initialize `qenv` with specific `env` and `code`. Such "break" should be implemented only in the classes which inherit from `qenv`. Thanks to this `qenv` will be simpler and more robust.

**Comment by donyunardi** [comment]
### Acceptance Criteria
* Remove `env` and `code from qenv construsctor`, `new_qenv`

**Comment by m7pr** [comment]
Is `new_qenv` renamed to `qenv` in the end?

**Comment by chlebowa** [comment]
[yes](https://github.com/insightsengineering/teal.code/pull/156)
