### ISSUE TITLE
[Question]: Should we clean the documentation of new_qenv?

### ISSUE THREAD

**Issue by m7pr** [insightsengineering/teal.code#150]
Described in here https://github.com/insightsengineering/teal.code/pull/146#pullrequestreview-1654732556

**Comment by chlebowa** [comment]
Speaking as the author of the original comment, I believe we should.
I would add `within` there as well, once #149 is merged.

**Comment by m7pr** [comment]
@chlebowa should I rename to `qenv` instead of `new_qenv`. Is this issue stil valid?

**Comment by chlebowa** [comment]
> @chlebowa should I rename to `qenv` instead of `new_qenv`. Is this issue stil valid?

No!
