### ISSUE TITLE
check reproducibility method

### ISSUE THREAD

**Issue by gogonzo** [insightsengineering/teal.code#151]
Blocked by https://github.com/insightsengineering/teal.data/issues/97

Method should check whether evaluation of the code generates the same environment as `@env`. Propose meaningful function name and implement

**Comment by chlebowa** [comment]
I think once we implement #145 this is redundant. Will still be required by `teal_data`. @gogonzo please move the issue if you agree.

**Comment by m7pr** [comment]
Not necessarily. This might be helpful to verify the reproducibility on any
step on qenv, not just on a creation. However I'm not sure what is the
benefit or the verification if a qenv that already was used in eval_code
twice has a reproducible environment based on its `code` slot

**Comment by chlebowa** [comment]
That's my point. If the evn is created empty and is only populated by evaluating code in ti, what is there to check?

> as used in eval_code twice

twice? :thinking:

**Comment by gogonzo** [comment]
> I think once we implement https://github.com/insightsengineering/teal.code/issues/145 this is redundant
Yes, I think we can close this issue in `teal.code` as there will be not possible (through public functions) to break class slots.

Instead, in `teal.data` we can have a special method to check validity
https://github.com/insightsengineering/teal.data/issues/182

**Comment by chlebowa** [comment]
Good :+1:
