### ISSUE TITLE
remove `teal.code`'s dependency

### ISSUE THREAD

**Issue by chlebowa** [insightsengineering/teal.code#158]
`teal.code` `Imports` `shiny`. The only use seems to be 
```
include_css_files <- function(pattern = "*") {
  css_files <- list.files(
    system.file("css", package = "teal.code", mustWork = TRUE),
    pattern = pattern, full.names = TRUE
  )
  if (length(css_files) == 0) {
    return(NULL)
  }

  shiny::singleton(lapply(css_files, shiny::includeCSS))
}
```

I say we drop `shiny` from dependencies. Please review other dependencies if we can drop any.

**Comment by chlebowa** [comment]
I believe `styler` and `lifecycle` can be dropped as well.

**Comment by gogonzo** [comment]
lifecycle not - it is need in imports to support badges

**Comment by chlebowa** [comment]
But there aren't any. Unless we expect to add some, then yes.

**Comment by m7pr** [comment]
remove `teal.code` or remove `shiny`?

**Comment by vedhav** [comment]
Looks like `include_css_files` is residual code along with the CSS file `debug_info_fa.css` which was evidently used by `get_eval_details_ui()`. So I guess they can go as well.
