### ISSUE TITLE
[Feature Request]: New `$` method to access objs from env

### ISSUE THREAD

**Issue by pawelru** [insightsengineering/teal.code#164]
### Feature description

Functionality identical to the `[[` but `$` would be a little bit more concise: `x["foo"]` vs `x$foo`.

todo:
- new method
- docs
- tests
- decide which one to promote as a _main_ one: `[[` or `$` - if the latter then change readme / examples / docs / vignettes and possibly docs in other packages as well

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

### Contribution Guidelines

- [X] I agree to follow this project's Contribution Guidelines.

### Security Policy

- [X] I agree to follow this project's Security Policy.

**Comment by m7pr** [comment]
@pawelru maybe we can have both?

And then, is it just

```r
`$.qenv` <- function(object, name) object[[name]]
```

**Comment by pawelru** [comment]
Yeah - we can definitely have both. This is a request for extension - not necessarily a replacement. However, it would be good to have one _preffered_ way of doing this so that our set of examples could follow a similar logic and be simpler to the end users

**Comment by llrs-roche** [comment]
With `$` working one could use .DollarNames.qenv to enable autocomplete (See ?.DollarNames with the dot) and recommend that way to access the data. This is relatively easy to do given all the other methods implemented but could have a big impact on how users write with the class.
