### ISSUE TITLE
code storage in `qenv.error`

### ISSUE THREAD

**Issue by chlebowa** [insightsengineering/teal.code#165]
The trace displayed by `get_code` called on `qenv.error` doesn't look right.

```
> qe <- qenv() |> within({IRIS = iris}) |> within(stop("oh no"))
> get_code(qe)
Error: oh no 
 when evaluating qenv code:
stop("oh no")

trace: 
 c("IRIS = iris", "stop(\"oh no\")")
```

I think when we changed `qenv@code` from `language` to `character` we forgot to adjust `qenv.error`.

**Comment by m7pr** [comment]
Hey, happy to take this one if you don't mind @chlebowa

**Comment by chlebowa** [comment]
Go for it :+1

**Comment by chlebowa** [comment]
The trace should contain all code up to and including the error. I just don't want to see a `c(` in there.

**Comment by m7pr** [comment]
Now it's clear

**Comment by m7pr** [comment]
Is this better?

```r
Error: oh no
when evaluating qenv code:
stop("oh no")

trace:
IRIS = iris
stop("oh no")
```

**Comment by chlebowa** [comment]
Yup, looks much better.
`print(qe)` still only shows the upper part, right?

**Comment by m7pr** [comment]
It does show to code up untill the whole `within` containing the error

```r
qe <- qenv() |> within({IRIS = iris}) |> within(stop("oh no")) |> within(head(iris))
get_code(qe)
qe <- qenv() |> 
  within(
    {IRIS = iris
    stop("oh no")
    head(iris)}
  ) |>
  within(
    cat(5)
  )
get_code(qe)
```


```r
> qe <- qenv() |> within({IRIS = iris}) |> within(stop("oh no")) |> within(head(iris))
> get_code(qe)
Error: oh no
when evaluating qenv code:
stop("oh no")

trace:
IRIS = iris
stop("oh no")
> qe <- qenv() |> 
+   within(
+     {IRIS = iris
+     stop("oh no")
+     head(iris)}
+   ) |>
+   within(
+     cat(5)
+   )
> get_code(qe)
Error: oh no
when evaluating qenv code:
stop("oh no")

trace:
IRIS = iris
stop("oh no")
head(iris)
```

**Comment by chlebowa** [comment]
Please read my question again.

**Comment by m7pr** [comment]
Looks like I didn't understand term `upper part` in your question, hence replied in the way you might be able to figure out the response on your own. If you couldn't figure this out based on the output, can you clarify what you meant by the `upper part`? Is `upper part` the `upper part` of the output (everything before `trace:` line), or the `upper part` of the `object@code` which would be all the code up until the error. I treated `upper part` as the portion of code we return out of `object@code` in the output after the line including `trace:`.

**Comment by chlebowa** [comment]
> Looks like I didn't understand term `upper part` in your question, hence replied in the way you might be able to figure out the response on your own.

And yet you didn't `print(qe)`.

**Comment by chlebowa** [comment]
![image](https://github.com/insightsengineering/teal.code/assets/114988527/eae1e0fb-6d68-405a-b787-0d23b4e1700a)

**Comment by m7pr** [comment]
Oh my,

```r
> print(qe)
<qenv.error: oh no 
 when evaluating qenv code:
stop("oh no")>
```

no excuses for my slow thinking today!

**Comment by chlebowa** [comment]
:+1:
