### ISSUE TITLE
get_code to return `character(1)` instead of `character(n)`

### ISSUE THREAD

**Issue by gogonzo** [insightsengineering/teal.code#173]
- `get_code` should return single string with all @code concatenated to a single string.

Please make relevant changes:
- We don't need to use `paste(get_code(...), collapse = "\n")` everywhere anymore. Please locate all `paste(collapse = "\n")` in `teal.modules.xyz` and in `teal` where code is concatenated to a single string.

**Comment by chlebowa** [comment]
The internal function `format_expression` can also be removed. It is used in very few places and that number will soon drop further.

**Comment by vedhav** [comment]
Maybe I'm missing something. Is there some reason that this issue is bucked into the wider `refactor` scope? I think it's fine to merge this directly into `main` without going through `refactor`.
