### ISSUE TITLE
[Feature Request]: Implement `names` argument in `get_code` to subset code for specific objects.

### ISSUE THREAD

**Issue by gogonzo** [insightsengineering/teal.code#210]
### Feature description

technically, it means to move `teal.data:::get_code_dependencies` to `teal.code`.
We also need to deprecate `teal.data::get_code` method and just use the `get_code` method from teal.code.

----

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

### Contribution Guidelines

- [X] I agree to follow this project's Contribution Guidelines.

### Security Policy

- [X] I agree to follow this project's Security Policy.

**Comment by donyunardi** [comment]
### Acceptance Criteria
* Move `teal.data:::get_code_dependency` to teal.code
* Deprecate `teal.data::get_code` method
* Review teal framework that's using `teal.data::get_code` and use `teal.code::get_code`
* Perform tests to ensure everything is working
