### ISSUE TITLE
Review Deprecated Functions

### ISSUE THREAD

**Issue by donyunardi** [insightsengineering/teal.code#215]
### Summary

Let's review the functions we deprecated in the previous release and decide whether to hard deprecate them (`lifecycle::deprecate_stop`) or remove them from the codebase entirely.

| Function | Action |
| --- | --- |
| [new_qenv](https://github.com/insightsengineering/teal.code/blob/2c580e9c6fe46190be3c6c44047e553ac994721e/R/qenv-constructor.R#L53-L56) | deprecate_stop |

**Comment by llrs-roche** [comment]
On the history there are several PR about [`deprecate_soft`](https://github.com/search?q=org%3Ainsightsengineering+is%3Apr+deprecate_soft+is%3Amerged&type=pullrequests) (most of them recent) and [`deprecate_stop`](https://github.com/search?q=org%3Ainsightsengineering+is%3Apr+deprecate_stop+is%3Amerged&type=pullrequests) also fairly recent.
But it is not easy to know what happen after that (git log or git rev-list don't work well on deleted files). 

I have prepared a PR that kept the function and help page but I have problems with the git configuration to create the branch/PR. Will resume on monday
