### ISSUE TITLE
[Feature Request]: Add new `get_messages` method. 

### ISSUE THREAD

**Issue by llrs-roche** [insightsengineering/teal.code#217]
### Feature description

The [qenv article](https://insightsengineering.github.io/teal.code/latest-tag/articles/qenv.html#warnings-and-messages-in-qenv-objects) exposes the internal representation of objects like `qenv@warnings` and `qenv@messages`.

It is [usually not recommended](https://contributions.bioconductor.org/r-code.html?q=slot#code-syntax-and-efficiency) to expose the internal object slots to users: this gives more freedom to developers to later change internal representations or even classes without users experimenting friction.  
There is a getter for `qenv@warnings`: `get_warnings()` but none for messages. An additional `get_messages()` method could avoid this situation. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

### Contribution Guidelines

- [X] I agree to follow this project's Contribution Guidelines.

### Security Policy

- [X] I agree to follow this project's Security Policy.

**Comment by m7pr** [comment]
@gogonzo I think this is vital functionality, as there is no way to work with qenv@messages right now. Should we add this function during #216 ?

**Comment by gogonzo** [comment]
@m7pr this can be addressed separately. Let's not complicate already complex PR 👍
