### ISSUE TITLE
[Bug]: test failure on windows and linux

### ISSUE THREAD

**Issue by gogonzo** [insightsengineering/teal.code#230]
### What happened?

https://github.com/r-universe/pharmaverse/actions/runs/11777449384/job/32802007063

**Comment by llrs-roche** [comment]
I've seen some changes on this [on R-devel](https://cran.r-project.org/doc/manuals/r-devel/NEWS.html):

> Inheritance information on S4 classes is maintained more consistently, particularly in the case of class unions (in part due to [PR#17596](https://bugs.r-project.org/show_bug.cgi?id=17596) and a report from Ezra Tucker).

Perhaps we are affected by this?

**Comment by gogonzo** [comment]
Hmmm, not sure, in `join.qenv`/`c.qenv` there is a `union(x@code, y@code)`. `x@code` is a list, so there is no S4 in this call.
