### ISSUE TITLE
Do not use instance$.__enclos_env__$

### ISSUE THREAD

**Issue by Polkas** [insightsengineering/teal.code#24]
If we have to use `$.__enclos_env__` something goes wrong with the class design.

`x_private <- x$.__enclos_env__$private`
https://github.com/insightsengineering/teal.code/blob/1d8daf67f31936b81a06ba88c12e2e16dc51ebc5/R/chunks.R#L212

and

https://github.com/insightsengineering/teal.code/blob/3a8ca32f77cd5f9111c78526342e5b2137b42923/R/chunks_pipe.R#L47

**Comment by Polkas** [comment]
It depends, as we will still will be supporting and maintaining chunks.
How much time we want to invest here.

**Comment by nikolas-burkoff** [comment]
I suggest we close this @donyunardi chunks are being deprecated and I don't see it worth investing time on code quality when it'll be removed soon

**Comment by donyunardi** [comment]
I agree @nikolas-burkoff
