### ISSUE TITLE
[teal.code] Discuss adding `logger` to `teal.code`

### ISSUE THREAD

**Issue by kpagacz** [insightsengineering/teal.code#3]
Are the logs needed? If so, where do we put them? This comment suggests logs could be useful in some methods:
![image](https://user-images.githubusercontent.com/24480246/158346536-656b25d2-f4de-461b-8bee-b9a005bb2312.png)

https://github.com/insightsengineering/teal.devel/pull/253#issuecomment-1066985681

**Comment by gogonzo** [comment]
Not relevant anymore
