### ISSUE TITLE
Rename quosure to qenv

### ISSUE THREAD

**Issue by gogonzo** [insightsengineering/teal.code#34]
Something which fits more and is short enough. I'd like to hear your propositions first.

**Comment by gogonzo** [comment]
See some discussion https://github.com/insightsengineering/teal.code/pull/49#discussion_r919888526

**Comment by gogonzo** [comment]
Here are some propositions:
- codenv
- repernv
- tealEnv
- envexp
- envcode
- envc ("c" as a shortcut of "code")
- envquo
- ecode / evcode ("e"/"ev" stands for "evaluated")
- ec
- ecc (evaluated code container)

Other question:
Do we want to keep it in teal.code or make a new package for this? If we make a new package then we won't need to go through deprecation process of `chunks`.

**Comment by donyunardi** [comment]
I'd vote for codenv or envcode.

If we make a new package, are we still going to maintain teal.code?
If yes, then would this possibly confuse user on which one to use?

**Comment by Polkas** [comment]
ecode or envcode

**Comment by mhallal1** [comment]
As we are already using `quosure` with `_q` everywhere, I would suggest `quoenv` or `qenv`.

**Comment by nikolas-burkoff** [comment]
Decided with qenv

**Comment by gogonzo** [comment]
Let's use this issue to replace quosure -> qenv in all repos

**Comment by pawelru** [comment]
Please don't forget to change filenames (using git mv to keep the history)
