### ISSUE TITLE
Enable usage of the pipe operator

### ISSUE THREAD

**Issue by gogonzo** [insightsengineering/teal.code#36]
In the modules only wrappers should be used instead of accessing chunks method directly.
Also, wrappers should have chunks object as a first argument and return chunks object to enable pipe operator.

For example:
```r
ch_object <- chunks_new() %>%
  chunks_reset() %>%
  chunks_push() %>% 
  chunks_push()
 
```

**Comment by donyunardi** [comment]
Once all quosure are finished, we can close this issue.

**Comment by gogonzo** [comment]
Quosures went through first review process. Already on the feature branch `teal_refactor@main`
