### ISSUE TITLE
Add tests to `remove_enclosing_curly_braces` and use for qenv?

### ISSUE THREAD

**Issue by nikolas-burkoff** [insightsengineering/teal.code#4]
And simplify - as the function is not nice at all

From https://github.com/insightsengineering/coredev-tasks/issues/147

**Comment by donyunardi** [comment]
@nikolas-burkoff 
Can we close this issue after `qenv` implementation?

**Comment by nikolas-burkoff** [comment]
Yes

**Comment by nikolas-burkoff** [comment]
So @donyunardi we can either remove this function entirely OR we can fix it and use it with qenvs to remove the extra "{" and "}" like we used to do with chunks 

Good spot @BLAZEWIM

**Comment by nikolas-burkoff** [comment]
ok so this function needs some tlc:

![image](https://user-images.githubusercontent.com/15201933/202206087-8b5b4ac8-f880-49c5-9c37-01bbb0fc50b3.png)

so n_spaces_indent is a vector of NA's and 4s and if there's at least one 4 then do the n_rm bit

**Comment by nikolas-burkoff** [comment]
This looks to be a simple replacement to the above - of course the above function may not be what we want...

```
remove_enclosing_curly_braces_replacement <- function(x) {

  if (length(x) == 0) return(x)

  open_bracket_then_spaces <- "^\\{[[:space:]]*"
  close_bracket_then_spaces <- "^\\}[[:space:]]*"
  blank_line <- "^[[:space:]]*$"
  four_spaces_at_start_of_line <- "^[[:space:]]{4}"

  split_text <- unlist(strsplit(x, "\n", fixed = TRUE))

  # if text begins with "{   \n" and ends with "\n}   "
  if (length(split_text) > 0 &&
    grepl(open_bracket_then_spaces, utils::head(split_text, 1)) &&
    grepl(close_bracket_then_spaces, utils::tail(split_text, 1))) {

    #remove the first and last line
    split_text <- split_text[-c(1, length(split_text))]

    # if any line is not blank then indent
    if (!all(grepl(blank_line, split_text))){
      gsub(four_spaces_at_start_of_line, "", split_text)
    }
  } else {
    return(split_text)
  }
}
```

**Comment by nikolas-burkoff** [comment]
This task is to

1) confirm the [above](https://github.com/insightsengineering/teal.code/issues/4#issuecomment-1317133673) function removes the curly brackets and realigns the code - feel free to improve on this/make it work if it doesn't
2) write tests to show its behaviour
3) use this function inside get_code() [here](https://github.com/insightsengineering/teal.code/blob/main/R/qenv-get_code.R#L27) so that brackets are being removed including in trace (and warnings output but this should be ok)
4) Fix any tests and check with tmg/tmc modules

Example teal app which should then be formatted nicely - this shows the show r code and the trace 

![image](https://user-images.githubusercontent.com/15201933/202214588-a6a5665b-c748-46e6-9e57-a7681528a50b.png)

```
library(teal.code)
library(teal.widgets)
library(shiny)


ui <- fluidPage(
  verbatim_popup_ui("button", "Press me")
)

server <- function(input, output, session) {
  q <- reactive({
    new_qenv(
      list2env(list(y = 2)), # add x = 1 here to remove the error
      code = quote({
        x <- 1
        y <- 2
      })
    ) |> eval_code(quote({
      if (x == 1) {
        print("x = 1")
      }
    }))
  })


  verbatim_popup_srv("button",
    verbatim_content = reactive(get_code(q())),
    title = "code"
  )
}

shinyApp(ui, server)
```

**Comment by nikolas-burkoff** [comment]
@lcd2yyz is happy for this to go ahead so I've unblocked
