### ISSUE TITLE
[Feature Request]: Qenv - force join of two qenv

### ISSUE THREAD

**Issue by gogonzo** [insightsengineering/teal.code#56]
### Feature description

Followup to @Polkas [comment](https://github.com/insightsengineering/teal.code/pull/49#issuecomment-1209286455)

It should be possible to ignore join protections and force appending of one quosure into another - see the outcome of the proposition:

```r
library(teal.code) # with my updates

q0 <- new_quosure(c("x <- 5"),
                  env = list2env(list(x = 5)))
q1 <- new_quosure(c("x <- 5", "y <- 10", "x <- 7"),
                  env = list2env(list(x = 7, y = 10)))
q2 <- new_quosure(c("x <- 5", "z <- x", "x <- 7"),
                  env = list2env(list(x = 7, z = 5)))

q3 <-  q0 |> eval_code(z <- 5)

q4 <-  q0 |> eval_code(t <- 5)

q5 <-  q0 |> eval_code(x <- 7)

join(q0, q1) # the same error for join(q0, q2)
#> Error in join(q0, q1): Not possible to join Quosure objects if anything in their environment has been modified.
#>  Following object(s) have been modified:
#>  -  x

get_code(join(q1, q2)) # all
#>     initial code   initial code.1   initial code.2   initial code.3 
#>         "x <- 5"        "y <- 10"         "x <- 7"         "x <- 5" 
#> initial code.1.1 initial code.2.1 
#>         "z <- x"         "x <- 7"

get_code(join(q0, q3))
#> initial code         code 
#>     "x <- 5"     "z <- 5"

get_code(join(q3, q4))
#> initial code         code       code.1 
#>     "x <- 5"     "z <- 5"     "t <- 5"

get_code(join(q3, q5)) # fail
#> Error in h(simpleError(msg, call)): error in evaluating the argument 'object' in selecting a method for function 'get_code': Not possible to join Quosure objects if anything in their environment has been modified.
#>  Following object(s) have been modified:
#>  -  x

get_code(join(q3, q5, resolve = FALSE)) # succcess
#>   initial code           code initial code.1         code.1 
#>       "x <- 5"       "z <- 5"       "x <- 5"       "x <- 7"
```

todo:
- Make a decision if this is needed first
- implement
- write tests

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

### Contribution Guidelines

- [X] I agree to follow this project's Contribution Guidelines.

### Security Policy

- [X] I agree to follow this project's Security Policy.

**Comment by gogonzo** [comment]
@nikolas-burkoff raised reproducibility problem with `join` when merging two quosures where both have some extra code:

```r
library(teal.code)

common_q <- new_quosure(w <- 1, env = list2env(list(w = 1)))

x_q <- eval_code(
  common_q,
  "x <- numeric(0)
for (i in 1:2) {
  x <- c(x, w)
  w <- w * 2
}"
)

y_q <- eval_code(
  common_q,
  "y <- numeric(0)
for (i in 1:2) {
  y <- c(y, w)
  w <- w * 2
}"
)


join_q <- join(x_q, y_q)

get_var(join_q, "y")
# this has y = c(1, 2)


# but:
code <- get_code(join_q)

cat(paste(code, collapse = "\n"))

# this gives

w <- 1
x <- numeric(0)
for (i in 1:2) {
  x <- c(x, w)
  w <- w * 2
}
y <- numeric(0)
for (i in 1:2) {
  y <- c(y, w)
  w <- w * 2
}

# which if run gives you y = c(4, 8)
```

In above `w` is modified in both environments but at the end it's identical, which means that it makes `join` vulnerable in some edge cases.
Please note that chunks doesn't capture that kind of object modification also.


P.S. Maybe we should check if `w` is different than `w` when quosures got split (keep pointer information somewhere?)

**Comment by nikolas-burkoff** [comment]
I guess it makes sense but the order you join the quosure's really matters as to whether you can join them or not:

```
library(teal.code)

common_q <- new_quosure(v <- 1, env = list2env(list(w = 1)))

x_q <- eval_code(
  common_q,
  "x <- v"
)

y_q <- eval_code(
  common_q,
  "y <- v"
)

z_q <- eval_code(
  y_q,
  "z <- v"
)


q_1 <- join(y_q, x_q)
q_2 <- join(x_q, y_q)

# works
join_q <- join(q_1, z_q)

# errors 
join_q <- join(q_2, z_q)
```

**Comment by nikolas-burkoff** [comment]
We need the `i <- NULL` or this fails...

![image](https://user-images.githubusercontent.com/15201933/185655889-79aa14bc-eb57-401f-8909-47bc322c942f.png)

**Comment by donyunardi** [comment]
Yeah, let's split it.
I'll open another one.

**Comment by donyunardi** [comment]
> 2) The comments from me about weird joining behaviour (which tbh may not be fixable, and just needs some education for module developers - the same behaviour existed in chunks I think?).

@nikolas-burkoff 
On second thought, I recalled we discussed about moving the point 2 to #71.
Would this be more efficient or is it better to treat it as a separate issue?

**Comment by Polkas** [comment]
@donyunardi for me the #71 is perfectly suited for the second part. THus we do not need additional issue.

**Comment by donyunardi** [comment]
As discussed, we will not move forward with this feature.
Thank you for the discussion everyone. 
We can resurrect this again when the needs arises.
