### ISSUE TITLE
Quosure - get operator should return a NULL for nomatch

### ISSUE THREAD

**Issue by Polkas** [insightsengineering/teal.code#57]
The Quosure get operator should return a NULL for nomatch, the same as chunks and base R environment / list.

```
ee <- new.env()
ee[["STH"]]
# NULL
ll <- list()
ll[["STH"]]
# NULL
```

**Comment by nikolas-burkoff** [comment]
After https://github.com/insightsengineering/teal.code/pull/65 there is a test showing we currently get an error in this case - during this issue, that test should be updated
