### ISSUE TITLE
Handle warnings and messages in qenv

### ISSUE THREAD

**Issue by nikolas-burkoff** [insightsengineering/teal.code#63]
https://github.com/insightsengineering/teal.code/pull/61 handles errors within chunks but not warnings or messages (nor outputs like print statements)

1) Store warnings and messages in `qenv` slots or maybe as atrtributes on the code slot items- see how this is done in chunks [here](https://github.com/insightsengineering/teal.code/blob/main/R/chunk.R#L98-L119) - the errors have been handled already?
2) Add `get_warning()` (and get_message() - though that probably won't be used) functions for `qenv` (make sure they work with `qenv.error` as well - could just return NULL or some error?) which could return NULL if there are no warnings
3) Have a `uiOutput` in the modules underneath/next to the show R code button
4) In renderUI have a `teal.widgets::verbatim_popup_ui` with say `req(get_warning(output_q()))` to make sure it's only shown if there's warnings - and clicking on the button shows the warnings
5) Make changes in teal.modules.general, teal.modules.clinical, teal.osprey, teal.gohawk and possibly 1 or 2 of teal's vignettes

Optionally: 6) If there are warnings created then display a notification when they are created  `shiny::showNotification`

Also update vignette in teal.code showing this functionality

Also add tests in teal.code for this functionality

Branch off teal_refactor@main onto x@teal_refactor@main for some x (same branch for all PRs)

**Comment by donyunardi** [comment]
Still need to discuss:
* How to show these message to the user
