### ISSUE TITLE
qenv to store code as expression

### ISSUE THREAD

**Issue by gogonzo** [insightsengineering/teal.code#67]
Followup to the @pawelru comments:
- https://github.com/insightsengineering/teal.code/pull/66#discussion_r972164927
- https://github.com/insightsengineering/teal.code/pull/66#discussion_r972236785

Since qenv returns ´quosure.error´ when failing, debug info module doesn't make sense so we don't need to store @code as a named character but as a expression. What is needed:
- remove eval_code.character method and move eval to the eval_code.expression
- remove new_quosure.character
- change all occurrences where 'eval_code' uses code as character
- remove all ´name´ in the eval_code
- change get_code to ´function(object, deparse = TRUE)´ - should still by default return the code as character with option ´deparse´ to optionally return expression

**Comment by nikolas-burkoff** [comment]
>  debug info module doesn't make sense

We still want to see warnings and messages somewhere though https://github.com/insightsengineering/teal.code/issues/63

**Comment by gogonzo** [comment]
> > debug info module doesn't make sense
> 
> We still want to see warnings and messages somewhere though #63

Sorry, my comment "doesn't make sense" wasn't decisive in this matter. We can still have slot for messages/warnings but there will be no names associated when displaying debug info.
