### ISSUE TITLE
[Suggestion] Modifying the slot design for the qenv class

### ISSUE THREAD

**Issue by pawelru** [insightsengineering/teal.code#70]
ID should be an attribute of each element of `code` vector. This would save you assertions of the length between those two and possibly more.

_Originally posted by @pawelru in https://github.com/insightsengineering/teal.code/pull/66#discussion_r972163426_

**Comment by donyunardi** [comment]
The class' slots has grown during development and with all the works that has been going in to the feature branch, maybe it'd be best if we reserve this for the next increment.

The team has reviewed this and assigned story point but still need to decide if this is necessary to do.

**Comment by gogonzo** [comment]
same applies to:
- warnings
- messages
