### ISSUE TITLE
Show method for `qenv` use `rlang::env_print`

### ISSUE THREAD

**Issue by nikolas-burkoff** [insightsengineering/teal.code#88]
Currently we print the contents of the environment ourselves - we could use rlang's function to do it for us

**Comment by asbates** [comment]
For reference, here is a comparison. I like how `rlang::env_print` shows a bulleted list of objects along with their types.


``` r
library(teal.code)

q <- new_qenv(env = list2env(list(a = 1)), code = quote(a <- 1))
q <- eval_code(q, quote(b <- "b"))

q
#> A qenv object containing: a, b
rlang::env_print(q@env)
#> <environment: 0x000002bee997a1e0> [L]
#> Parent: <environment: package:teal.code>
#> Bindings:
#> • a: <dbl> [L]
#> • b: <chr> [L]
```

<sup>Created on 2022-12-29 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>
