### ISSUE TITLE
Multiple warnings for the same code are not separated by new line characters

### ISSUE THREAD

**Issue by nikolas-burkoff** [insightsengineering/teal.code#89]
Example from `tm_g_spiderplot` in `teal.osprey` but does this matter? 

![image](https://user-images.githubusercontent.com/15201933/199827415-5fb35479-4d21-4dad-a357-1ae6226a51eb.png)

This comes from [here](https://github.com/insightsengineering/teal.code/blob/main/R/qenv-eval_code.R#L54)

If we do add "\n" we need to make sure:
- the first time we call paste0 it does not add a "\n" before the first warning
- the get_warning function creates a sensibly formatted string
- tests should be updated

**Comment by donyunardi** [comment]
### Acceptance Criteria
* Each warning should be presented as a new line.

**Comment by nikolas-burkoff** [comment]
So there are two parts the first is making sure the warnings from the code [here](https://github.com/insightsengineering/teal.code/blob/main/R/qenv-eval_code.R#L54) get added with new lines separating them  and the second part is to make sure the `get_warnings` function returns a nicely formatted string.

Reprex:
```
q <- eval_code(new_qenv(), quote("iris_data <- iris"))
q <- eval_code(q, quote("p <- hist(iris_data[, 'Sepal.Length'], ff = '')"))
q <- eval_code(q, quote(warning("this is a single warning"))) 
q@warnings
get_warnings(q)
```
